language: rust
rust: stable
cache: cargo

jobs:
  include:
    - stage: test
      addons:
        apt:
          packages:
            - libsdl2-dev

    - stage: deploy
      if: type != pull_request AND branch = master
      rust: nightly
      script: ./docs.sh
      deploy:
        provider: pages
        github-token: $GH_TOKEN
        local-dir: target/doc

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
