os: linux
language: rust
rust: stable
cache: cargo

jobs:
  include:
    - stage: test
      addons:
        apt:
          packages:
            - libsdl2-dev
      before_script:
        - rustup component add rustfmt clippy
      script:
        - cargo build --verbose
        - cargo test --verbose
        - cargo fmt -- --check
        - cargo clippy --verbose

    - stage: deploy
      if: type != pull_request AND branch = master
      rust: nightly
      script: ./docs.sh
      deploy:
        provider: pages
        skip_cleanup: true
        token: $GH_TOKEN
        local_dir: target/doc

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
