name: CI
on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain (nightly)
        id: install_rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          default: true
      - name: Install SDL2
        run: sudo apt-get install libsdl2-dev

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust-${{ steps.install_rust.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ steps.install_rust.outputs.rustc_hash }}-

      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --verbose --workspace --all-targets

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --workspace

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --verbose --all -- --check

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --verbose --workspace

  upload_docs:
    name: Upload documentation
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain (stable)
        id: install_rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust-${{ steps.install_rust.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ steps.install_rust.outputs.rustc_hash }}-

      - name: Generate documentation
        run: ./docs.sh --verbose

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: target/doc
          single-commit: true
